@Library('jenkins-shared-pipeline-library') _

pipeline {
  agent none
  stages {
    agent { label 'aws-ec2' }
    stage ('CI') {
      steps {
        def customImage = docker.build("my-image:${env.BUILD_ID}")
        sh "docker run --rm -p 8080:8080 --name myapi ${customImage.id}"
      }
    }
  }
}