@Library('jenkins-shared-pipeline-library') _

pipeline {
  agent none
  environment {
    customImage = null
    AWS_DEFAULT_REGION = "us-east-1"
  }
  stages {
    stage ('CI') {
      agent{
        node {
          label 'aws-ec2'
        }
      }
      steps {
        script{
          customImage = docker.build("my-image:${env.BUILD_ID}")
        }
        println "success build image: ${customImage.id}"
      }
    }
  }
}